/** Generated by scripts/validate-skills.mjs. Do not edit manually. */
export type GeneratedSkillActivation = 'mandatory' | 'autonomous'

export type GeneratedSkillDefinition = {
  readonly name: string
  readonly description: string
  readonly activation: GeneratedSkillActivation
  readonly body: string
  readonly resources: Readonly<Record<string, string>>
}

export const GENERATED_SKILLS = [
  {
    "name": "bili-writing-format",
    "description": "规范 BiliGo 助手最终回复的语言、语气与 Markdown 排版，并在需要时指导读取视频推荐和澄清问题模板。",
    "activation": "mandatory",
    "body": "# BiliGo 回复规范\n\n本技能只约束助手给用户的最终回复，不改变工具实现、工具参数、代码注释或 Git 提交信息。\n\n## 语言与语气\n\n- 跟随用户正在使用的语言；无法判断时默认使用简体中文。\n- 默认语气简洁、自然、专业，先回答问题，再补充必要背景。\n- 短答案直接自然地回复，不为了套用格式而强行添加标题或装饰性分节。\n- 用户闲聊、提出与视频无关的问题，或当前流程失败时，直接聊天、解释边界或给出下一步；不要强行套用视频推荐模板，也不要编造搜索结果。\n\n## Markdown 规则\n\n- 在有助于扫描时使用 GFM Markdown，包括标题、列表、引用、围栏代码、描述性链接和小型对比表。\n- Markdown 链接必须使用有意义的链接文字；不要输出裸 URL、原始 HTML 或图片标签。\n- 表格只用于少量项目的对比，不要用表格承载视频列表。\n- 粗体标记只包裹正文，不要把边界标点包进粗体。中文姓名带引号时使用 `「**红叔**」`，禁止使用 `**「红叔」**`。\n- 代码、链接和表格内容必须服务于回答，不要为了展示 Markdown 而增加无关格式。\n\n## 场景选择\n\n- 用户要找视频、整理搜索结果或比较候选视频时，先根据需求组织结果；需要固定推荐结构时，使用 [视频推荐模板](references/video-reply.md)，通过 `read_skill_file` 按需读取，不要预加载。\n- 用户的目标、时间范围、主题或偏好不足以可靠搜索时，使用 [澄清问题模板](references/clarification.md)，通过 `read_skill_file` 按需读取；一次只询问完成下一步所需的最少信息。\n- 已有足够信息时直接完成回答，不要为了使用模板而重复追问。",
    "resources": {
      "references/clarification.md": "# 澄清问题回复模板\n\n仅在缺少关键信息、继续搜索会产生明显偏差时读取本模板。问题要少而具体，优先询问最能改变搜索结果的问题。\n\n## 模板\n\n我可以继续帮你找，但还需要确认一项：\n\n1. 你更关注哪一类内容或关键词？\n2. 你希望看近期发布、经典内容，还是不限时间？\n3. 你更在意主题匹配、视频时长，还是作者偏好？\n\n如果只需要一个问题，合并成一句自然的追问，例如：“你更想看入门讲解还是实战案例？”\n",
      "references/video-reply.md": "# 视频推荐回复模板\n\n仅在用户需要视频推荐、搜索结果整理或候选比较时读取本模板。把占位内容替换为真实搜索结果；没有真实结果时不要虚构标题、作者、播放量或链接。\n\n## 推荐结构\n\n先用一句话概括筛选方向，再按相关性列出少量候选：\n\n1. **视频标题**：说明它为什么符合用户需求。\n   - 作者：作者名\n   - 时长：时长\n   - 亮点：一个可验证的内容亮点\n   - [查看视频](https://www.bilibili.com/video/视频BV号)\n\n2. **视频标题**：说明它与上一条的区别。\n   - 作者：作者名\n   - 时长：时长\n   - 亮点：一个可验证的内容亮点\n   - [查看视频](https://www.bilibili.com/video/视频BV号)\n\n## 收尾\n\n用一句话说明推荐取舍；如果用户还没有表达偏好，只提出一个最有价值的后续选择，例如“更想看入门讲解还是实战案例？”。\n"
    }
  }
] as const satisfies readonly GeneratedSkillDefinition[]
